# Generated by Django 5.1.4 on 2026-01-23 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('avatar_color', models.CharField(default='#e94560', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
