# Generated by Django 5.1.4 on 2026-01-23 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('setup', 'Configurando'), ('mulligans', 'Mulligans'), ('active', 'Em Andamento'), ('paused', 'Pausado'), ('finished', 'Finalizado')], default='setup', max_length=20)),
                ('turn_number', models.PositiveIntegerField(default=0)),
                ('active_player_seat', models.PositiveSmallIntegerField(default=0)),
                ('current_phase', models.CharField(choices=[('untap', 'Desvirar'), ('upkeep', 'Manutencao'), ('draw', 'Compra'), ('main1', 'Primeira Fase Principal'), ('combat_begin', 'Inicio do Combate'), ('combat_attackers', 'Declarar Atacantes'), ('combat_blockers', 'Declarar Bloqueadores'), ('combat_damage', 'Dano de Combate'), ('combat_end', 'Fim do Combate'), ('main2', 'Segunda Fase Principal'), ('end', 'Fase Final'), ('cleanup', 'Limpeza')], default='untap', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_position', models.PositiveSmallIntegerField()),
                ('life', models.IntegerField(default=40)),
                ('poison_counters', models.PositiveSmallIntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('has_lost', models.BooleanField(default=False)),
                ('has_won', models.BooleanField(default=False)),
                ('lands_played_this_turn', models.PositiveSmallIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.deck')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile')),
            ],
            options={
                'ordering': ['seat_position'],
                'unique_together': {('game', 'seat_position')},
            },
        ),
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('library', 'Biblioteca'), ('hand', 'Mao'), ('battlefield', 'Campo de Batalha'), ('graveyard', 'Cemiterio'), ('exile', 'Exilio'), ('command', 'Zona de Comando'), ('stack', 'Pilha')], max_length=20)),
                ('zone_position', models.PositiveIntegerField(default=0)),
                ('is_tapped', models.BooleanField(default=False)),
                ('is_face_down', models.BooleanField(default=False)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('damage_marked', models.PositiveIntegerField(default=0)),
                ('is_commander', models.BooleanField(default=False)),
                ('commander_cast_count', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='game.game')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_objects', to='game.gameplayer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to='game.gameplayer')),
            ],
            options={
                'ordering': ['zone', 'zone_position'],
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('game_start', 'Inicio do Jogo'), ('draw', 'Comprar'), ('play_land', 'Jogar Terreno'), ('cast_spell', 'Lancar Magia'), ('activate', 'Ativar Habilidade'), ('tap', 'Virar'), ('untap', 'Desvirar'), ('attack', 'Atacar'), ('block', 'Bloquear'), ('damage', 'Dano'), ('life_change', 'Mudanca de Vida'), ('zone_change', 'Mudanca de Zona'), ('counter_change', 'Mudanca de Marcadores'), ('phase_change', 'Mudanca de Fase'), ('turn_change', 'Mudanca de Turno'), ('concede', 'Conceder'), ('win', 'Vitoria'), ('lose', 'Derrota'), ('chat', 'Chat'), ('manual', 'Acao Manual')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('display_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('turn_number', models.PositiveIntegerField()),
                ('phase', models.CharField(max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gameplayer')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='game.gameplayer'),
        ),
        migrations.CreateModel(
            name='CommanderDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.PositiveIntegerField(default=0)),
                ('commander_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commander_damage', to='game.game')),
                ('source_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commander_damage_dealt', to='game.gameplayer')),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commander_damage_received', to='game.gameplayer')),
            ],
            options={
                'unique_together': {('game', 'target_player', 'source_player', 'commander_card')},
            },
        ),
    ]
