# Generated by Django 5.1.4 on 2026-01-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('game', '0003_add_battlefield_row_and_reveal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='is_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='token_abilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='token_colors',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='token_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='token_power',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='token_toughness',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='token_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameobject',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.card'),
        ),
    ]
