# Generated by Django 5.1.4 on 2026-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_token_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaction',
            name='action_type',
            field=models.CharField(choices=[('game_start', 'Inicio do Jogo'), ('draw', 'Comprar'), ('play_land', 'Jogar Terreno'), ('cast_spell', 'Lancar Magia'), ('activate', 'Ativar Habilidade'), ('tap', 'Virar'), ('untap', 'Desvirar'), ('attack', 'Atacar'), ('block', 'Bloquear'), ('damage', 'Dano'), ('life_change', 'Mudanca de Vida'), ('zone_change', 'Mudanca de Zona'), ('counter_change', 'Mudanca de Marcadores'), ('phase_change', 'Mudanca de Fase'), ('turn_change', 'Mudanca de Turno'), ('concede', 'Conceder'), ('win', 'Vitoria'), ('lose', 'Derrota'), ('chat', 'Chat'), ('manual', 'Acao Manual'), ('scry', 'Videncia'), ('look_top', 'Ver Topo'), ('put_top', 'Colocar no Topo'), ('put_bottom', 'Colocar no Fundo'), ('reveal', 'Revelar'), ('shuffle_into', 'Embaralhar Dentro'), ('create_token', 'Criar Token')], max_length=20),
        ),
    ]
