# Generated by Django 5.1.4 on 2026-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_create_token_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='is_transformed',
            field=models.BooleanField(default=False),
        ),
    ]
