# Generated by Django 5.1.4 on 2026-01-23 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('decks', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Partida Commander', max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando Jogadores'), ('ready', 'Pronto para Iniciar'), ('in_game', 'Em Jogo'), ('finished', 'Finalizado')], default='waiting', max_length=20)),
                ('min_players', models.PositiveSmallIntegerField(default=2)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby', to='game.game')),
            ],
            options={
                'verbose_name_plural': 'Lobbies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('seat_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decks.deck')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lobby.lobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('lobby', 'player')},
            },
        ),
    ]
