# Generated by Django 5.1.4 on 2026-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('cmc', models.FloatField(default=0)),
                ('type_line', models.CharField(db_index=True, max_length=255)),
                ('oracle_text', models.TextField(blank=True, null=True)),
                ('colors', models.CharField(blank=True, default='', max_length=50)),
                ('color_identity', models.CharField(blank=True, default='', max_length=50)),
                ('set_code', models.CharField(db_index=True, max_length=10)),
                ('set_name', models.CharField(max_length=255)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic'), ('special', 'Special'), ('bonus', 'Bonus')], max_length=20)),
                ('image_small', models.URLField(blank=True, max_length=500, null=True)),
                ('image_normal', models.URLField(blank=True, max_length=500, null=True)),
                ('image_large', models.URLField(blank=True, max_length=500, null=True)),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
